package com.andreih.stocks.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF494FBF)
val md_theme_light_onPrimary = Color(0xFFFFFBFF)
val md_theme_light_primaryContainer = Color(0x26494FBF)
val md_theme_light_onPrimaryContainer = Color(0xFF1A1C40)
val md_theme_light_secondary = Color(0xFF0F1359)
val md_theme_light_onSecondary = Color(0xFFFFFBFF)
val md_theme_light_secondaryContainer = Color(0xFF1A1C40)
val md_theme_light_onSecondaryContainer = Color(0xFFFFFBFF)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_success = Color(0xFF49BF59)
val md_theme_light_onError = Color(0xFFFFFBFF)
val md_theme_light_background = Color(0xFFFFFBFF)
val md_theme_light_onBackground = Color(0xFF1A1C40)
val md_theme_light_surface = Color(0xFFFFFBFF)
val md_theme_light_onSurface = Color(0xFF1A1C40)
val md_theme_light_outline = Color(0xFF767680)

val md_theme_dark_primary = Color(0xFF494FBF)
val md_theme_dark_onPrimary = Color(0xFFFFFBFF)
val md_theme_dark_primaryContainer = Color(0x26494FBF)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFFBFF)
val md_theme_dark_secondary = Color(0xFF0F1359)
val md_theme_dark_onSecondary = Color(0xFFFFFBFF)
val md_theme_dark_secondaryContainer = Color(0xFF1A1C40)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFFBFF)
val md_theme_dark_error = Color(0xFFD33A3A)
val md_theme_dark_success = Color(0xFF49BF59)
val md_theme_dark_onError = Color(0xFFFFFBFF)
val md_theme_dark_background = Color(0xFF1A1C40)
val md_theme_dark_onBackground = Color(0xFFFFFBFF)
val md_theme_dark_surface = Color(0xFF1A1C40)
val md_theme_dark_onSurface = Color(0xFFFFFBFF)
val md_theme_dark_outline = Color(0xFF90909A)