name: Unit & Instrumented Test

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

concurrency:
  group: stocks-test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Cache Gradle Files
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches/
            ~/.gradle/wrapper/
          key: cache-gradle

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Setup CI properties
        run: cp local.properties.ci local.properties

      - name: Build and Test with Gradle
        run: ./gradlew clean assembleDebug testDebugUnitTest

      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }} # IMPORTANT: run Android Test Report regardless

      - name: Upload Debug APK
        uses: actions/upload-artifact@v1
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Build androidTest APK
        run: ./gradlew clean assembleDebugAndroidTest

      - name: Upload androidTest APK
        uses: actions/upload-artifact@v1
        with:
          name: app-debug-androidTest
          path: app/build/outputs/apk/androidTest/debug/app-debug-androidTest.apk

  instrumented-test:
    runs-on: ubuntu-latest
    needs: unit-test
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Download debug APK
        uses: actions/download-artifact@v1
        with:
          name: app-debug

      - name: Download androidTest APK
        uses: actions/download-artifact@v1
        with:
          name: app-debug-androidTest

      - name: Login to Google Cloud
        uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_key: ${{ secrets.GCLOUD_AUTH }}

      - name: Set Firebase Project
        run: gcloud config set project ${{ secrets.FIREBASE_PROJECT_ID }}

      - name: Run Instrumentation Tests in Firebase Test Lab
        run: gcloud firebase test android run --type instrumentation --use-orchestrator --app app-debug/app-debug.apk --test app-debug-androidTest/app-debug-androidTest.apk --device model=oriole,version=33,orientation=portrait
